<?xml version="1.0" encoding="utf-8"?><Database Name="QLKaraoke" Class="QLKaraokeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-7SG3LH3\SQLEXPRESS;Initial Catalog=QLKaraoke;Integrated Security=True" SettingsObjectName="BLL_DAL.Properties.Settings" SettingsPropertyName="QLKaraokeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietHoaDon" Member="ChiTietHoaDons">
    <Type Name="ChiTietHoaDon">
      <Column Name="IDHoaDon" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDDichVu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="DichVu_ChiTietHoaDon" Member="DichVu" ThisKey="IDDichVu" OtherKey="ID" Type="DichVu" IsForeignKey="true" />
      <Association Name="HoaDon_ChiTietHoaDon" Member="HoaDon" ThisKey="IDHoaDon" OtherKey="ID" Type="HoaDon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GiaPhongTheoGio" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IDLoaiPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Phong_HoaDon" Member="HoaDons" ThisKey="ID" OtherKey="IDPhong" Type="HoaDon" />
      <Association Name="LoaiPhong_Phong" Member="LoaiPhong" ThisKey="IDLoaiPhong" OtherKey="ID" Type="LoaiPhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DichVu" Member="DichVus">
    <Type Name="DichVu">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDichVu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IDLoaiDichVu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DichVu_ChiTietHoaDon" Member="ChiTietHoaDons" ThisKey="ID" OtherKey="IDDichVu" Type="ChiTietHoaDon" />
      <Association Name="LoaiDichVu_DichVu" Member="LoaiDichVu" ThisKey="IDLoaiDichVu" OtherKey="ID" Type="LoaiDichVu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioVao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GioRa" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GioHat" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TienGio" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="HoaDon_ChiTietHoaDon" Member="ChiTietHoaDons" ThisKey="ID" OtherKey="IDHoaDon" Type="ChiTietHoaDon" />
      <Association Name="Phong_HoaDon" Member="Phong" ThisKey="IDPhong" OtherKey="ID" Type="Phong" IsForeignKey="true" />
      <Association Name="NhanVien_HoaDon" Member="NhanVien" ThisKey="IDNhanVien" OtherKey="ID" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiDichVu" Member="LoaiDichVus">
    <Type Name="LoaiDichVu">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiDV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="LoaiDichVu_DichVu" Member="DichVus" ThisKey="ID" OtherKey="IDLoaiDichVu" Type="DichVu" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhong" Member="LoaiPhongs">
    <Type Name="LoaiPhong">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="LoaiPhong_Phong" Member="Phongs" ThisKey="ID" OtherKey="IDLoaiPhong" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.ManHinh" Member="ManHinhs">
    <Type Name="ManHinh">
      <Column Name="MaManHinh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenManHinh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="ManHinh_PhanQuyen" Member="PhanQuyens" ThisKey="MaManHinh" OtherKey="MaManHinh" Type="PhanQuyen" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="UserName" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IDNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PhanQuyen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NguoiDung_NguoiDungNhomNguoiDung" Member="NguoiDungNhomNguoiDungs" ThisKey="UserName" OtherKey="UserName" Type="NguoiDungNhomNguoiDung" />
      <Association Name="NhanVien_NguoiDung" Member="NhanVien" ThisKey="IDNhanVien" OtherKey="ID" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDungNhomNguoiDung" Member="NguoiDungNhomNguoiDungs">
    <Type Name="NguoiDungNhomNguoiDung">
      <Column Name="UserName" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDNhomNguoiDung" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="NguoiDung_NguoiDungNhomNguoiDung" Member="NguoiDung" ThisKey="UserName" OtherKey="UserName" Type="NguoiDung" IsForeignKey="true" />
      <Association Name="NhomNguoiDung_NguoiDungNhomNguoiDung" Member="NhomNguoiDung" ThisKey="IDNhomNguoiDung" OtherKey="ID" Type="NhomNguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="NhanVien_HoaDon" Member="HoaDons" ThisKey="ID" OtherKey="IDNhanVien" Type="HoaDon" />
      <Association Name="NhanVien_NguoiDung" Member="NguoiDungs" ThisKey="ID" OtherKey="IDNhanVien" Type="NguoiDung" />
    </Type>
  </Table>
  <Table Name="dbo.NhomNguoiDung" Member="NhomNguoiDungs">
    <Type Name="NhomNguoiDung">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNhomNguoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="NhomNguoiDung_NguoiDungNhomNguoiDung" Member="NguoiDungNhomNguoiDungs" ThisKey="ID" OtherKey="IDNhomNguoiDung" Type="NguoiDungNhomNguoiDung" />
      <Association Name="NhomNguoiDung_PhanQuyen" Member="PhanQuyens" ThisKey="ID" OtherKey="MaNhomNguoiDung" Type="PhanQuyen" />
    </Type>
  </Table>
  <Table Name="dbo.PhanQuyen" Member="PhanQuyens">
    <Type Name="PhanQuyen">
      <Column Name="MaNhomNguoiDung" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaManHinh" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CoQuyen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="ManHinh_PhanQuyen" Member="ManHinh" ThisKey="MaManHinh" OtherKey="MaManHinh" Type="ManHinh" IsForeignKey="true" />
      <Association Name="NhomNguoiDung_PhanQuyen" Member="NhomNguoiDung" ThisKey="MaNhomNguoiDung" OtherKey="ID" Type="NhomNguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
</Database>